---
version: "3"

services:
  webapp:
    image: fbm95/results_img
    ports:
      - 1222:1222
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

# docker run -d --name results -p 1221:1221 results_img
